#!/bin/bash

_subberthehut() 
{
	local cur="${COMP_WORDS[COMP_CWORD]}"

	local opts="-h -v -l -L -a -n -f -o -O -s -t -e -q
	            --help --version --lang --list-languages
	            --always-ask --never-ask
	            --force --hash-search-only --name-search-only
	            --same-name --limit --no-exit-on-fail --quiet"

	if [[ $cur == -* ]]; then
		COMPREPLY=( $(compgen -W "$opts" -- $cur) )
	else
		mapfile -t COMPREPLY < <(compgen -f -- $cur)
	fi
}

complete -o plusdirs -F _subberthehut subberthehut
